version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

parameters:
  workspace:
    type: string
    default: hqo

  orb-name:
    type: string
    default: circleci-api

orbs:
  orb-tools: circleci/orb-tools@11.1.2
  shellcheck: circleci/shellcheck@3.1.0

commands:
  check_version:
    steps:
      - run:
          name: Install / upgrade the CircleCI CLI
          command: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | sudo bash
      - run:
          name: Assert tag version is unpublished
          command: |
            [[ "$(circleci orb list << pipeline.parameters.workspace >> | grep "<< pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>" | grep -oE "[0-9].[0-9].[0-9]")" != "${CIRCLE_TAG}" ]]
jobs:
  check_version:
    executor: default
    resource_class: small
    steps:
      - check_version

workflows:
  on-tag:
    jobs:
      - check_version:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'

      - orb-tools/pack:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'

      - orb-tools/publish:
          name: publish production orb
          enable-pr-comment: false
          vcs-type: << pipeline.project.type >>
          orb-name: << pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>
          pub-type: production
          requires:
            - orb-tools/pack
            - check_version
          context:
            - orb-publishing
            - github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[0-9]+\.[0-9]+\.[0-9]+$/'

  on-commit:
    jobs:
      # Run a bunch of tests against this repo
      - orb-tools/lint:
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore:
                - /.*/

      - orb-tools/pack:
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore:
                - /.*/

      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore:
                - /.*/

      - orb-tools/publish:
          name: publish development orb
          enable-pr-comment: true
          vcs-type: << pipeline.project.type >>
          orb-name: << pipeline.parameters.workspace >>/<< pipeline.parameters.orb-name >>
          pub-type: dev
          requires:
            - orb-tools/pack
            - orb-tools/lint
            - shellcheck/check
          context:
            - orb-publishing
            - github
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore:
                - /.*/
